#!/bin/sh

# Hamy - www.hamy.io

# Any error, should result in script failure
set -e

PREREQ="dropbear"
DB_INIT_BTM_ORG="$DESTDIR/scripts/init-bottom/dropbear"
DB_INIT_BTM_TMP="$DESTDIR/scripts/init-bottom/dropbear-int-btm-fix.tmp1"
BB_INIT_ORG="$DESTDIR/bin/busybox"
COMMANDS_LIST="md5sum cut cp patch mv"
OLD_IFS="$IFS"
DB_INIT_VER=""

# Handles errors
error_out()
{
  echo "************* WARNING *************"
  echo "$1"
  # If we have created the tmp file, it's time to delete it
  if [ -f "$DB_INIT_BTM_TMP" ]; then
    rm "$DB_INIT_BTM_TMP" || echo "Could not delete \"$DB_INIT_BTM_TMP\""
  fi
  echo "\"$0\" will not be applied"
  echo "***********************************"
  # exit code is always 0 so it wouldn't stop the initram build.
  # This means that worst case scenario, this script would simply
  # act as if it hadn't been existed.
  exit 0
}

# Calculating md5 hashes
md5hash()
{
  echo $(md5sum "$1" | cut -d ' ' -f 1)
}

# Handles the prereqs functionality of the initramfs-tools
prereqs()
{
  echo "$PREREQ"
}

# Protect the script from direct execution
if [ "$DESTDIR" = "" ]; then
  echo "Error: This script is not be run directly" >&2
  exit 1
fi

# Handles the prereqs functionality of the initramfs-tools
case $1 in
  prereqs)
    prereqs
    exit 0
    ;;
esac

# Ensuring all the required commands exist
IFS=" "
for i in $COMMANDS_LIST; do
  if ! command -v $i >/dev/null; then
    error_out "\"$i\" command not be found in PATH (how is that even possible?)"
  fi
done
IFS="$OLD_IFS"

# We need to import the provided hook functions
[ -r /usr/share/initramfs-tools/hook-functions ] || error_out "Could not find the hook functions"
. /usr/share/initramfs-tools/hook-functions

# Is busybox disabled in initramfs.conf?
[ n = "$BUSYBOX" ] && error_out "busybox utilities are disabled for initram"

# Testing the presence of dropbear init-bottom script
[ -x "$DB_INIT_BTM_ORG" ] || error_out "Could not find dropbear init-bottom script (is dropbear-initramfs installed?)"
[ -h "$DB_INIT_BTM_ORG" ] && error_out "dropbear init-bottom script is a symlink (why?)"

# Supported versions must be specifically added here. This is to reduce the chance
# of breaking things after an upgrade to dropbear-initramfs. If the script in question
# doesn't change between upgrades though, it might still work.
case "$(md5hash $DB_INIT_BTM_ORG)" in
  # v2017.75-3build1
  506f966b4f3df7fdb41f98d5d54fd9e4)
    DB_INIT_VER=75
    ;; 
  *)
    error_out "dropbear init-bottom script hash did not match. This is probably due to updates to dropbear-initramfs package. This calls for a new evaluation of the script (the patch might not be needed anymore)."
    ;;
esac

# Check the existence of the original busybox binary added by busybox-initramfs
[ -x "$BB_INIT_ORG" ] || error_out "Could not find busybox location in initram"

# Ensure the original busybox lacks extended options.
# We do this by actually executing the initram busybox. This should be safe
# as non-root users, are not allowed to make changes to the binary.
if $BB_INIT_ORG ps -o ppid >/dev/null 2>&1; then
  error_out "busybox initram, seems to be supporting extended options now. No patch is needed"
fi

# We do the patching on a tmp file first
if ! cp -p "$DB_INIT_BTM_ORG" "$DB_INIT_BTM_TMP"; then
  error_out "Could not create the tmp file"
fi

# This is where the magic happens. Basically, it fixes the
# offending commands in dropbear init-bottom script (the arguments 
# originally used in those commands, require a busybox build with 
# the support of extended options). Based on the supported versions, 
# we patch them and to top it off, we check the md5 hash of the pacthed 
# file.
case $DB_INIT_VER in
  75)
    # This patch is ported from dropbear-initramfs 2018.76-5 in debian 10
    if ! patch -s "$DB_INIT_BTM_TMP" <<'EOF'
@@ -28,2 +28,2 @@
-    ps -o ppid= -o pid= -o pgid= | \
-        sed -nr "s/^\s*$PID\s+([0-9]+)\s+\1\s*$/\1/p" | \
+    sed -nr "s/^([0-9]+) \\(.*\\) \\S $PID \\1 .*/\\1/p" \
+        /proc/[0-9]*/stat 2>/dev/null | \
@@ -33,2 +33,2 @@
-    ps -o ppid= -o pid= | \
-        sed -nr "s/^\s*$PID\s+([0-9]+)\s*$/\1/p" | \
+    sed -nr "s/^([0-9]+) \\(.*\\) \\S $PID [0-9]+ .*/\\1/p" \
+        /proc/[0-9]*/stat 2>/dev/null | \
EOF
    then
      error_out "could not apply the patch"
    fi
    [ "$(md5hash $DB_INIT_BTM_TMP)" = "5424920866450179ec08b486eb60f531" ] || error_out "patch hash mismatch"
    ;;
  *)
    error_out "Could not match against any valid patch (This should have never happened)"
    ;;
esac

# Now it should be safe to replace the original dropbear init-bottom script.
# This is the last step and it really should not fail at this point, but if it does,
# we're not going to handle it. Instead, we let the script fail so initram build is stopped.
# That way the user can investigate wth is going on.
mv -f "$DB_INIT_BTM_TMP" "$DB_INIT_BTM_ORG"

# And we are done!
echo "successfully applied: $0"

